Models/Department.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LeadManagementSystem.Models
{
    [Table("DepartmentMaster")]
    public class Department
    {
        [Key]
        public int DepartmentId { set; get; }

        [MaxLength(250)]
        public string DepartmentName { set; get; }

        public DateTime CreatedOn { set; get; }
        public DateTime UpdatedOn { set; get; }
        public DateTime DeletedOn { set; get; }

        public int CreatedBy { set; get; }
        public int UpdatedBy { set; get; }
        public int DeletedBy { set; get; }
   
    }
}

Models/Designation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LeadManagementSystem.Models
{
    [Table("DesignationMaster")]
    public class Designation
    {
        public int DesignationId { set; get; }

        [MaxLength(512)]
        public string DesignationTitle { set; get; }

    }
}

Models/Lead.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LeadManagementSystem.Models
{
    public class Lead
    {
        public int LeadId { set; get; }

        [MaxLength(512)]
        public string Name { set; get; }

        [MaxLength(512)]
        public string LeadSource { set; get; }
        public string LeadUrl { set; get; }
        public string LeadDetails { set; get; }
        
        [NotMapped]
        public string GeneratedBy { set; get; }
    }
}

Models/LeadAssign.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LeadManagementSystem.Models
{

    [Table("LeadAssign")]
    public class LeadAssign
    {
       public int LeadAssignId { set; get; }
        public int LeadId { set; get; }
        public int AssignTo { set; get; }
        public int AssignBy { set; get; }
        public DateTime AssignedOn { set; get; }
        public int ReadFlag { set; get; }
        public int RecordStatus { set; get; }
    }
}

Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LeadManagementSystem.Models
{
    [Table("tblUser")]
    public class User
    {
        [Key]
        public int UserId { set; get; }

        [MaxLength(512)]
        public string UserName { set; get; }


        [MaxLength(50)]
        public string FirstName { set; get; }

        [MaxLength(50)]
        public string LastName { set; get; }

        [MaxLength(512)]
        [Required]
        public string Email { set; get; }


        [MaxLength(512)]
        [DataType(DataType.Password)]
        public string Passwd { set; get; }

        public DateTime CreatedOn { set; get; }
        public DateTime UpdatedOn { set; get; }
        public DateTime DeletedOn { set; get; }

        public int CreatedBy { set; get; }
        public int UpdatedBy { set; get; }
        public int DeletedBy { set; get; }
        public int DepartmentId { set; get; }
        public decimal Salary { set; get; }

        public int DesignationId { set; get; }


        public bool isSuccess { set; get; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LeadManagementSystem.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using LeadManagementSystem.Models;
using LeadManagementSystem.Repo;
using System.Data;

namespace LeadManagementSystem.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(User oUser)
        {
            //Validate User credential in database. 
            DataTable obj = new DataTable();


            obj = LoginRepo.LoginCheck(oUser);

            if(obj != null && obj.Rows.Count > 0)
            {
                for (int i = 0; i < obj.Rows.Count; i++)
                {
                    oUser.isSuccess = true;
                    oUser.UserId = Convert.ToInt32(obj.Rows[i]["UserId"]);
                    oUser.FirstName = Convert.ToString(obj.Rows[i]["FirstName"]);
                    oUser.LastName = Convert.ToString(obj.Rows[i]["LastName"]);
                    //oUser.DesignationId = Convert.ToInt32(obj.Rows[i]["DesignationId"]);
                }
            }
            else
            {
                oUser.isSuccess = false;
            }
            
            return Json(oUser, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Login/Index.cshtml
@{ Layout = null; }
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
@*<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>*@
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>
    <title>Login Page</title>
    <!--Made with love by Mutiullah Samim -->
    <!--Bootsrap 4 CDN-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!--Fontawesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <!--Custom styles-->
    <link href="~/Content/Login.css" rel="stylesheet" />
    <script>
        function onSuccess(res) {
            alert(1);

        }
        function onFailed() {
            alert("Failed ajax call");
        }
    </script>

</head>
<body>
    <div class="container">
        <div class="d-flex justify-content-center h-100">
            <div class="card">
                <div class="card-header">
                    <h3>Sign In</h3>

                </div>
                <div class="card-body">
                    @using (Ajax.BeginForm("Index", "Login", new AjaxOptions { HttpMethod = "POST", OnSuccess = "onSuccess", OnFailure="onFailed" }))
                            {
                        
                        <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" class="form-control" placeholder="username" id="Email" name="Email" value="martandmadhwani@gmail.com">
                        <span id="msgusername"></span>
                    </div>
                                    <div class="input-group form-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                                        </div>
                                        <input type="password" class="form-control" placeholder="password" id="txtpassword" name="Passwd" value="password@123">
                                        <span id="msgpassword"></span>
                                    </div> @*<div class="row align-items-center remember">
                                            <input type="checkbox">Remember Me
                                        </div>*@
                                                    <div class="form-group">
                                                        <input type="submit" value="Login" class="btn float-right login_btn" id="btnLogin">
                                                    </div>}



                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-center links">
                        Don't have an account?<a href="#">Sign Up</a>
                    </div>
                    @*<div class="d-flex justify-content-center">
                            <a href="#">Forgot Password?</a>
                        </div>*@
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>